AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - db/**/*
    - config/**/*
    - log/**/*
    - tmp/**/*
    - bin/**/*

Metrics/LineLength:
  Max: 125

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb
